/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.testallservicesforvcs.myjavaservice122.controller;

import com.testallservicesforvcs.myjavaservice122.MyJavaService122;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/myJavaService122")
public class MyJavaService122Controller {

    @Autowired
    private MyJavaService122 myJavaService122;

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return myJavaService122.sampleJavaOperation(name, request);
    }
}
