/*Copyright (c) 2016-2017 vcstest4.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest4.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest4.com*/
package com.testallservicesforvcs.adventureworks2014.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetdeptInfoResponse implements Serializable {


    @JsonProperty("Name")
    @ColumnAlias("Name")
    private String name;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetdeptInfoResponse)) return false;
        final GetdeptInfoResponse getdeptInfoResponse = (GetdeptInfoResponse) o;
        return Objects.equals(getName(), getdeptInfoResponse.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName());
    }
}
