/*Copyright (c) 2016-2017 vcstest4.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest4.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest4.com*/

package com.testallservicesforvcs.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testallservicesforvcs.adventureworks2014.models.procedure.*;

@Service
public class AdventureWorks2014ProcedureExecutorServiceImpl implements AdventureWorks2014ProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AdventureWorks2014ProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014WMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public GetdeptInfoResponse executeGetdeptInfo(Integer deptid) {
        Map params = new HashMap(2);

        params.put("deptid", deptid);

        return procedureExecutor.executeNamedProcedure("GetdeptInfo", params, GetdeptInfoResponse.class);
    }

}


