/*Copyright (c) 2016-2017 vcstest4.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest4.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest4.com*/
package com.testallservicesforvcs.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testallservicesforvcs.adventureworks2014.service.AdventureWorks2014ProcedureExecutorService;
import com.testallservicesforvcs.adventureworks2014.models.procedure.*;

@RestController(value = "AdventureWorks2014.ProcedureExecutionController")
@RequestMapping("/AdventureWorks2014/procedureExecutor")
@Api(value = "ProcedureExecutionController", description = "controller class for procedure execution")
public class ProcedureExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcedureExecutionController.class);

    @Autowired
    private AdventureWorks2014ProcedureExecutorService procedureService;

    @RequestMapping(value = "/procedure/execute/GetdeptInfo", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "d")
    public List<GetdeptInfoResponse> executeGetdeptInfo(@RequestParam(value = "deptid", required = false) Integer deptid, HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: GetdeptInfo");
        GetdeptInfoResponse _result = procedureService.executeGetdeptInfo(deptid);
        LOGGER.debug("got the result for v1 named procedure: GetdeptInfo, result:{}", _result);
        return Collections.singletonList(_result);
    }

}


